[package]
name = "Rust_OCR"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "*", features = ["rand", "serde-serialize"] }
bincode = "*"
serde = { version = "1.0.216", features = ["derive"] }
minifb = "*"

