[package]
name = "digit_ocr_nn"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
config = "*"
minifb = "*"
walkdir = "*"
rayon = "*"
byteorder = "*"
lazy_static = "*"
